#==========================================================================
# Description: upload files.
#==========================================================================

name: files-upload-new-tags
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_tag_name:
        description: "请输入tag_name."
        required: false
        default: ""
        type: string
      set_url0:
        description: "请输入url0."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
      set_url1:
        description: "请输入url1."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
      set_url2:
        description: "请输入url2."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
      set_url3:
        description: "请输入url3."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
      set_url4:
        description: "请输入url4."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
      set_url5:
        description: "请输入url5."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
      set_url6:
        description: "请输入url6."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
      set_url7:
        description: "请输入url7."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
      set_url8:
        description: "请输入url8."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
      set_url9:
        description: "请输入url9."
        required: false
        default: "https://qq.com/xxx.txt"
        type: string
     # set_url9:
        # description: "请输入url."
        # required: false
        # default: " "
        # type: string
env:
  TZ: Etc/UTC

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # 初始化环境
      - name: Initialize the build environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi -f $(docker images -q) 2>/dev/null || true
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          # sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          # sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-build-armbian-depends)
          sudo -E systemctl daemon-reload
          # sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo -E timedatectl set-timezone "${TZ:-Etc/UTC}"
          sudo -E ntpdate ntp.ubuntu.com 0.pool.ntp.org || true
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}
      # 创建模拟物理磁盘
      - name: Create virtual disk for extended storage
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}
      # 下载源代码
      - name: mkdir_build
        id: down
        working-directory: /builder
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: |
          df -hT ${PWD}          
          mkdir -p build
          ln -sf /builder/build ${GITHUB_WORKSPACE}/build
          echo "status=success" >> $GITHUB_OUTPUT

        # 编译 Armbian
      - name: wget files [ ${{ inputs.set_release }} ]
        id: compile
        working-directory: /builder
        if: ${{ steps.down.outputs.status == 'success' && !cancelled() }}
        run: |
          # 编译方法及参数说明: https://docs.armbian.com/Developer-Guide_Build-Options
          # sudo timedatectl set-timezone Asia/Shanghai          
          sudo timedatectl set-ntp true
          timedatectl
          cd build/
          mkdir -p output && mkdir -p output/images          
          cd output/images/
          # wget https://github.com/minimal.img.xz
          touch "Upload_${{inputs.set_tag_name}}_$(date +"%Y-%m-%d_%H-%M-%S").txt"  
          # && ls -l >> Upload_rk3318_imgs_$(date +"%Y-%m-%d_%H-%M-%S").txt
          # touch "Upload_$(date +"%Y-%m-%d_%H-%M-%S").txt"  &&  ${{ inputs.set_url }} >> Upload_$(date +"%Y-%m-%d_%H-%M-%S").txt && wget -i Upload_$(date +"%Y-%m-%d_%H-%M-%S").txt
          # if [ -n "${{ inputs.set_url0 }}" ]; then wget "${{ inputs.set_url0 }}"; fi
          urls=(
          "${{ inputs.set_url0 }}"
          "${{ inputs.set_url1 }}"
          "${{ inputs.set_url2 }}"
          "${{ inputs.set_url3 }}"
          "${{ inputs.set_url4 }}"
          "${{ inputs.set_url5 }}"
          "${{ inputs.set_url6 }}"
          "${{ inputs.set_url7 }}"
          "${{ inputs.set_url8 }}"
          "${{ inputs.set_url9 }}"
          )
          for url in "${urls[@]}"; do
              if [ -n "$url" ]; then
                  echo "Downloading $url"
                  wget --tries=3 --timeout=30 "$url"
                  if [ $? -ne 0 ]; then
                      echo "::error::Failed to download $url"
                      exit 1
                      fi
                      fi
                      done
          find . -maxdepth 1 -type f -name "*xxx*" -exec rm -fv {} +
          # sudo split -b 1990M build.tar.xz build.tar.xz.part-          
          tag_img=$(ls -t *.txt| head -n 1)
          # TAG_BASENAME=$(basename "$tag_img" .txt)   
          TAG_BASENAME=${{inputs.set_tag_name}}
          # sudo xz -9 *.img          
          # timestamp=$(date +%Y%m%d%H%M%S)
          txt_file=$(find . -maxdepth 1 -type f -name "*.txt" | head -n 1)
          if [ -z "$txt_file" ]; then
          echo "未找到任何打包文件。"
          exit 1
          fi             
          echo "status=success" >> $GITHUB_OUTPUT
          echo "TAG_BASENAME=${TAG_BASENAME}" >> $GITHUB_OUTPUT  # 供后续步骤使用
          
          
      - name: Upload Armbian image to Release
        uses: ncipollo/release-action@main
        if: ${{ steps.compile.outputs.status == 'success' && !cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        with:
          # tag: armbian-img
          artifacts: build/output/images/*
          skipIfReleaseExists: true          
          tag:  ${{ steps.compile.outputs.TAG_BASENAME }}
