name: Upload Assets to Existing Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Existing tag name"
        required: true

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download files
        run: |
          mkdir downloads
          while IFS= read -r url || [ -n "$url" ]; do
            [ -z "$url" ] && continue
            curl -L -o "downloads/$(basename "$url")" "$url"
          done < urls.txt

      - name: Upload to Release
        env:
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.inputs.tag_name }}
        run: |
          for file in downloads/*; do
            echo "Uploading $file"
            gh release upload "$TAG_NAME" "$file" --clobber
          done
